[tool.poetry]
name = "tests_notebooks"
version = "0.1.0"
description = ""
authors = ["Alina Astrakova <alina.astrakova@cognite.com>"]

[tool.black]
line-length=120
target_version = ['py37']
include = '\.py$'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '^((?!py$).)*$'    # this makes sort all Python files

[tool.poetry.dependencies]
python = "^3.7"
cognite-sdk = "^1.4"
numpy = "^1.17"
pandas = "^0.25"
jupyter = "^1"
cognite-datastudio = "=0.1.8"
jupytext = "^1.3.2"

[tool.poetry.dev-dependencies]
black = "^19.3b0"
isort = "^4.3"
pytest = "^5.3.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
pytest = "^5.2"
